import type { Metadata } from 'next';
import { Lato } from 'next/font/google';

import './globals.css';
import HeaderComponent from '@/components/Header';

import ThemeContext from '@/lib/contexts/ThemeContext';

import Wrapper from './Wrapper';

const lato = Lato({
	weight: ['400', '300', '700'], // Specify the weights you need
	subsets: ['latin'], // Specify subsets if needed
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<html lang="en">
				<head />
				<body className={lato.className}>
					<ThemeContext>
						<Wrapper>
							<HeaderComponent />
							{children}
						</Wrapper>
					</ThemeContext>
				</body>
			</html>
		</>
	);
}
