import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import HeaderComponent from '@/components/Header';

import ThemeContext from '@/lib/contexts/ThemeContext';

import Wrapper from './Wrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<html lang="en">
				<head />
				<body className={inter.className}>
					<ThemeContext>
						<Wrapper>
							<HeaderComponent />
							{children}
						</Wrapper>
					</ThemeContext>
				</body>
			</html>
		</>
	);
}
